#include <algorithm>
#include <filesystem>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "cartograph/graph.hpp"
#include "cartograph/indexer.hpp"

namespace {

std::filesystem::path linkage_dir() {
  return std::filesystem::path(FIXTURE_DIR) / "linkage";
}

// NodeId of the definition of `name` whose file basename is `file`. Fails the
// test if the (name, file) pair does not identify exactly one definition, so a
// miswired fixture surfaces as a clear error rather than a bad lookup.
cartograph::NodeId def_in(const cartograph::Graph& graph, const std::string& name,
                          const std::string& file) {
  std::vector<cartograph::NodeId> matches;
  for (const cartograph::NodeId id : graph.nodes_named(name)) {
    if (std::filesystem::path(graph.node(id).file).filename() == file) {
      matches.push_back(id);
    }
  }
  EXPECT_EQ(matches.size(), 1u)
      << "expected exactly one '" << name << "' in " << file;
  return matches.empty() ? cartograph::NodeId{0} : matches.front();
}

// Sorted names of the functions that call the definition `id` — the resolved
// callers, independent of iteration order.
std::vector<std::string> caller_names(const cartograph::Graph& graph,
                                      cartograph::NodeId id) {
  std::vector<std::string> out;
  for (const cartograph::NodeId caller : graph.callers_of(id)) {
    out.emplace_back(graph.node(caller).name);
  }
  std::sort(out.begin(), out.end());
  return out;
}

}  // namespace

// A call in a file that has a local `static` definition of the name resolves to
// that local definition — never to an external one of the same name elsewhere.
TEST(Linkage, LocalStaticShadowsExternal) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());

  const cartograph::NodeId local = def_in(graph, "shade", "local_static.c");
  const cartograph::NodeId external = def_in(graph, "shade", "local_extern.c");

  EXPECT_EQ(caller_names(graph, local),
            (std::vector<std::string>{"uses_local"}));
  EXPECT_TRUE(caller_names(graph, external).empty())
      << "external shade must not capture the local caller";
}

// With no local static definition, a call resolves to the external definition
// in another file.
TEST(Linkage, ResolvesToExternalAcrossFiles) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());

  const cartograph::NodeId provide = def_in(graph, "provide", "extern_def.c");
  EXPECT_EQ(caller_names(graph, provide),
            (std::vector<std::string>{"uses_extern"}));
}

// Two files each defining `static impl`, each with its own caller: every caller
// resolves to its own file's definition, not the other's. This is the case
// naive name-matching links to both.
TEST(Linkage, TwoLocalStaticsResolveRespectively) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());

  const cartograph::NodeId impl_a = def_in(graph, "impl", "static_a.c");
  const cartograph::NodeId impl_b = def_in(graph, "impl", "static_b.c");

  EXPECT_EQ(caller_names(graph, impl_a), (std::vector<std::string>{"entry_a"}));
  EXPECT_EQ(caller_names(graph, impl_b), (std::vector<std::string>{"entry_b"}));
}

// Documented limitation: a call generated by a function-like macro produces no
// CALLS edge, because the preprocessor is not run and the macro is not expanded.
TEST(Linkage, MacroGeneratedCallHasNoEdge) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());

  const cartograph::NodeId target = def_in(graph, "target", "macro.c");
  EXPECT_TRUE(caller_names(graph, target).empty())
      << "macro-generated call must not create a CALLS edge to target";
}

// A call to a name with two external definitions (a real C link error) is
// linked to both and surfaced as a diagnostic naming the callee and its
// candidates — rather than silently resolved to one.
TEST(Linkage, ConflictingExternalsAreLinkedAndFlagged) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());

  const cartograph::NodeId clash_a = def_in(graph, "clash", "conflict_a.c");
  const cartograph::NodeId clash_b = def_in(graph, "clash", "conflict_b.c");

  // Linked to every candidate.
  EXPECT_EQ(caller_names(graph, clash_a),
            (std::vector<std::string>{"conflict_caller"}));
  EXPECT_EQ(caller_names(graph, clash_b),
            (std::vector<std::string>{"conflict_caller"}));

  // And flagged: exactly one diagnostic for `clash`, listing both definitions.
  std::vector<const cartograph::Diagnostic*> clash_diags;
  for (const cartograph::Diagnostic& d : graph.diagnostics()) {
    if (d.callee == "clash") clash_diags.push_back(&d);
  }
  ASSERT_EQ(clash_diags.size(), 1u);
  EXPECT_EQ(std::filesystem::path(clash_diags.front()->caller_file).filename(),
            "conflict_call.c");
  EXPECT_EQ(clash_diags.front()->caller_line, 4u);
  EXPECT_EQ(clash_diags.front()->candidates.size(), 2u);
}

// A call resolving to a single external definition is not a conflict and must
// not be flagged.
TEST(Linkage, UnambiguousResolutionIsNotFlagged) {
  const cartograph::Graph graph = cartograph::index_directory(linkage_dir());
  for (const cartograph::Diagnostic& d : graph.diagnostics()) {
    EXPECT_NE(d.callee, "provide");
    EXPECT_NE(d.callee, "shade");
  }
}
